spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: EMPLOYEE-PROVIDER-DEV
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka-7001.com:7001/eureka  #告诉服务提供者要把服务注册到哪儿 #单机环境
  instance:
    prefer-ip-address: true #显示客户端真实ip
---
server:
  port: 8002
spring:
  profiles: pro
  application:
    name: PRODUCT-PROVIDER-DEV
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka-7001.com:7001/eureka  #告诉服务提供者要把服务注册到哪儿 #单机环境
  instance:
    prefer-ip-address: true #显示客户端真实ip
---
server:
  port: 8101
spring:
  profiles: test
  application:
    name: EMPLOYEE-PROVIDER-TEST
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka-7001.com:7001/eureka  #告诉服务提供者要把服务注册到哪儿 #单机环境
  instance:
    prefer-ip-address: true #显示客户端真实ip

